AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template EC2 Instance

Parameters: 
  InstanceType: 
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      -m4.2xlarge
    
  
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-41e0b93b 
      InstanceType: !Ref InstanceType
      KeyName: praveenkey
      SecurityGroupIds: 
         - sg-35f03d42
Outputs:
  EC2InstancePublicIPAddress:
    Description: 'The public IP address of the EC2 Instance.'
    Value: !GetAtt EC2Instance.PublicDnsName
    
